"use client";
import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from "recharts";
import { Activity, ArrowDownLeft, ArrowRight, ArrowUpRight, Cable, CalendarDays, Check, ChevronLeft, ChevronRight, CircleHelp, Download, Gem, Landmark, LayoutDashboard, RefreshCw, Search, ShieldCheck, Wallet, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { NativeSelect } from "@/components/ui/native-select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { currentMonth, demoData, money, summarize, weeklyFlow, type FinanceData, type Transaction } from "@/lib/finance";
import type { AppConfig } from "@/lib/app-config";
import AccountPanel from "./account-panel";

type View = "overview" | "transactions" | "accounts" | "plans";
const iconMap = { dashboard: LayoutDashboard, activity: Activity, landmark: Landmark, gem: Gem } as const;
const dateText = (date: string) => new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(date));

export default function Dashboard({ initialConfig }: { initialConfig: AppConfig }) {
  const { settings, navigation, plans: planConfig } = initialConfig;
  const [month, setMonth] = useState(currentMonth);
  const [data, setData] = useState<FinanceData>(() => demoData(currentMonth()));
  const [view, setView] = useState<View>(() => (navigation.find(item => item.slug === "overview")?.slug || navigation[0]?.slug || "overview") as View);
  const [bank, setBank] = useState("all"), [kind, setKind] = useState("all"), [search, setSearch] = useState(""), [page, setPage] = useState(1);
  const [connect, setConnect] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [detail, setDetail] = useState<Transaction | null>(null);
  const [identity, setIdentity] = useState<{ email: string; plan: string } | null>(null);
  useEffect(() => {
    const change = () => { const v = window.location.hash.slice(1); if (navigation.some(i => i.slug === v)) { setView(v as View); setPage(1); } };
    change(); window.addEventListener("hashchange", change);
    return () => window.removeEventListener("hashchange", change);
  }, [navigation]);
  const navigate = (next: View) => { setView(next); window.location.hash = next; setPage(1); };
  const scoped = useMemo(() => data.transactions.filter(t => bank === "all" || t.bank_account_id === bank), [data, bank]);
  const totals = summarize(scoped), chart = weeklyFlow(scoped, month);
  const accounts = data.accounts.filter(a => bank === "all" || a.id === bank);
  const filtered = useMemo(() => scoped.filter(t => (kind === "all" || t.transfer_type === kind) && `${t.transaction_content} ${t.reference_number} ${t.account_number}`.toLocaleLowerCase("vi").includes(search.toLocaleLowerCase("vi"))), [scoped, kind, search]);
  const pages = Math.max(1, Math.ceil(filtered.length / 6)), shown = filtered.slice((page - 1) * 6, page * 6);
  const monthLabel = `Tháng ${Number(month.slice(5))}, ${month.slice(0, 4)}`;
  const activeNav = navigation.find(item => item.slug === view) || navigation[0];

  async function sync(selectedMonth = month) {
    setBusy(true); setError(""); setNotice("");
    try {
      const res = await fetch(`/api/sepay/dashboard?month=${encodeURIComponent(selectedMonth)}`, { cache: "no-store" });
      const body = await res.json();
      if (res.status === 401 || body.code === "CONNECTION_REQUIRED") setConnect(true);
      if (!res.ok) throw new Error(body.message || "Chưa thể lấy dữ liệu. Vui lòng thử lại.");
      setData(body); setMonth(selectedMonth); setPage(1); setBank("all");
      setNotice(body.mode === "demo" ? "Đã cập nhật dữ liệu mẫu. Đăng nhập và kết nối SePay để xem giao dịch thật." : "Đã lấy giao dịch mới nhất từ SePay.");
    } catch (e) { setError(e instanceof Error ? e.message : "Không thể kết nối máy chủ."); }
    finally { setBusy(false); }
  }
  function changeMonth(value: string) { if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(value)) return; if (data.mode === "live") void sync(value); else { setMonth(value); setData(demoData(value)); setPage(1); } }
  function exportCsv() {
    const safe = (v: string | number) => `"${String(v).replace(/^[=+@\-\t\r]/, "'$&").replaceAll('"', '""')}"`;
    const rows = [["Thời gian", "Nội dung", "Ngân hàng", "Số tài khoản", "Thu (VND)", "Chi (VND)", "Mã tham chiếu"], ...filtered.map(t => [t.transaction_date, t.transaction_content, t.bank_brand_name, t.account_number, t.amount_in, t.amount_out, t.reference_number])];
    const url = URL.createObjectURL(new Blob(["\uFEFF" + rows.map(r => r.map(safe).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" }));
    const a = document.createElement("a"); a.href = url; a.download = `finflow-${data.mode}-${month}.csv`; a.click(); URL.revokeObjectURL(url); setNotice(`Đã xuất ${filtered.length} giao dịch${data.mode === "demo" ? " mẫu" : ""}.`);
  }
  return <div className="app-shell">
    <a className="skip-link" href="#main">Đến nội dung chính</a>
    <aside className="sidebar"><a className="brand" href={`#${navigation[0]?.slug || "overview"}`} onClick={() => navigate((navigation[0]?.slug || "overview") as View)}><span className="brand-mark"><Activity size={23} strokeWidth={2.7} /></span>{settings.brand_name}<span className="brand-dot">.</span></a>
      <div className="workspace"><span className="workspace-icon"><Wallet size={20} /></span><div><strong>{settings.workspace_name}</strong><span>{identity ? settings.member_workspace_label : settings.guest_workspace_label}</span></div></div>
      <p className="nav-label">{settings.nav_section_label}</p><nav aria-label="Điều hướng chính">{navigation.map(item => { const Icon = iconMap[item.icon_key]; return <Button key={item.slug} variant="ghost" className={`nav-button ${view === item.slug ? "active" : ""}`} onClick={() => navigate(item.slug as View)} aria-current={view === item.slug ? "page" : undefined}><Icon size={19} />{item.title}</Button>; })}</nav>
      <div className="sidebar-bottom"><div className="sepay-box"><span><Cable size={19} />{settings.sidebar_card_title}</span><p>{settings.sidebar_card_description}</p><Button variant="ghost" onClick={() => setConnect(true)}>{settings.sidebar_card_action}<ArrowRight size={16} /></Button></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb">{settings.workspace_name}<ChevronRight size={14} /><strong>{activeNav?.title}</strong></div><div className="topbar-right"><span className={`status-pill ${data.mode === "live" ? "live" : ""}`}><span />{data.mode === "demo" ? settings.demo_status_label : settings.live_status_label}</span><Button variant="ghost" size="icon" className="help-button" aria-label="Hướng dẫn và tài khoản" onClick={() => setConnect(true)}><CircleHelp size={20} /></Button><Button variant="ghost" className="avatar-button" onClick={() => setConnect(true)} aria-label="Mở tài khoản">{identity ? identity.email.slice(0, 1).toUpperCase() : settings.brand_name.slice(0, 1).toUpperCase()}</Button></div></header>
    <main id="main"><div className="page-heading"><div><div className="eyebrow">{settings.eyebrow}</div><h1>{activeNav?.page_title}</h1><p>{activeNav?.page_description}</p></div>{view !== "plans" && <Button onClick={() => sync()} disabled={busy} className="sync-button"><RefreshCw size={17} className={busy ? "spin" : ""} />{busy ? "Đang đồng bộ…" : "Đồng bộ SePay"}</Button>}</div>
    {view !== "plans" && <div className="period-bar"><div className="period-controls"><label className="month-control"><CalendarDays size={17} /><span className="sr-only">Tháng xem giao dịch</span><input type="month" value={month} min="2020-01" max="2100-12" onChange={e => changeMonth(e.target.value)} disabled={busy} /></label><NativeSelect aria-label="Lọc tài khoản ngân hàng" value={bank} onChange={e => { setBank(e.target.value); setPage(1); }}><option value="all">Tất cả tài khoản</option>{data.accounts.map(a => <option key={a.id} value={a.id}>{a.bank_short_name} · {a.account_number.slice(-4)}</option>)}</NativeSelect></div><span className="update-note">{data.mode === "demo" ? "Dữ liệu mẫu để trải nghiệm" : data.fetchedAt ? `Cập nhật ${dateText(data.fetchedAt)}` : "Chưa đồng bộ"}</span></div>}
    {error && <div role="alert" className="feedback error"><span>{error}</span><Button variant="ghost" size="icon" aria-label="Đóng lỗi" onClick={() => setError("")}><X size={16} /></Button></div>}{notice && <div role="status" className="feedback"><Check size={17} /><span>{notice}</span><Button variant="ghost" size="icon" aria-label="Đóng thông báo" onClick={() => setNotice("")}><X size={16} /></Button></div>}
    {!data.complete && <div className="feedback warning">Đã tải {data.transactions.length}/{data.total} giao dịch. Tổng thu chi và biểu đồ chỉ tính các giao dịch đã tải.</div>}
    {view === "overview" && <><section className="stats-grid" aria-label="Tóm tắt tài chính">
      <div className="stat-card balance-card"><div className="stat-label">Tổng số dư tài khoản<Wallet size={19} /></div><strong>{money(accounts.reduce((s, a) => s + a.accumulated, 0))}</strong><div className="stat-footer"><span>{accounts.length} tài khoản {data.mode === "demo" ? "mẫu" : "ngân hàng"}</span><span>VND</span></div></div>
      <div className="stat-card"><div className="stat-label">Tổng tiền vào<span className="stat-icon positive"><ArrowDownLeft size={19} /></span></div><strong>{money(totals.income)}</strong><div className="stat-footer"><span className="positive">{scoped.filter(t => t.transfer_type === "in").length} giao dịch thu</span><span>Trong tháng</span></div></div>
      <div className="stat-card"><div className="stat-label">Tổng tiền ra<span className="stat-icon negative"><ArrowUpRight size={19} /></span></div><strong>{money(totals.expense)}</strong><div className="stat-footer"><span className="negative">{scoped.filter(t => t.transfer_type === "out").length} giao dịch chi</span><span>Trong tháng</span></div></div>
      <div className="stat-card"><div className="stat-label">Dòng tiền ròng<span className="stat-icon blue"><Activity size={19} /></span></div><strong className={totals.net >= 0 ? "positive" : "negative"}>{totals.net > 0 ? "+" : ""}{money(totals.net)}</strong><div className="stat-footer"><span>Tiền vào − tiền ra</span><span>VND</span></div></div>
    </section><div className="analytics-grid"><section className="panel chart-panel"><div className="section-heading"><div><h2>Dòng tiền trong tháng</h2><p>Thu và chi theo từng tuần · VND</p></div><div className="chart-legend"><span><i />Tiền vào</span><span><i />Tiền ra</span></div></div><ChartContainer config={{ income: { label: "Tiền vào", color: "#3563ed" }, expense: { label: "Tiền ra", color: "#edaa55" } }} className="flow-chart"><AreaChart accessibilityLayer data={chart} margin={{ left: 0, right: 10, top: 18, bottom: 0 }}><defs><linearGradient id="incomeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3563ed" stopOpacity={0.18} /><stop offset="95%" stopColor="#3563ed" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="4 5" /><XAxis dataKey="name" axisLine={false} tickLine={false} tickMargin={14} /><YAxis axisLine={false} tickLine={false} width={56} tickFormatter={v => `${v / 1000000}tr`} /><ChartTooltip content={<ChartTooltipContent formatter={(v, name) => <span>{name === "income" ? "Tiền vào" : "Tiền ra"}: <strong>{money(Number(v))}</strong></span>} />} /><Area isAnimationActive={false} type="monotone" dataKey="income" stroke="#3563ed" strokeWidth={3} fill="url(#incomeFill)" /><Area isAnimationActive={false} type="monotone" dataKey="expense" stroke="#edaa55" strokeWidth={2.5} fill="transparent" strokeDasharray="5 4" /></AreaChart></ChartContainer><div className="chart-bottom"><span>{monthLabel}</span><span>Dòng tiền ròng <strong className={totals.net >= 0 ? "positive" : "negative"}>{money(totals.net)}</strong></span></div></section>
      <section className="panel accounts-panel"><div className="section-heading"><h2>Tài khoản của bạn</h2><Landmark size={19} /></div><div className="account-list">{accounts.map(a => <div className="account-summary" key={a.id}><span className={`bank-logo ${a.bank_short_name.includes("MB") ? "mb" : "vcb"}`}><Landmark size={21} /></span><div className="account-name"><strong>{a.bank_short_name}</strong><span>•••• {a.account_number.slice(-4)}</span></div><strong>{money(a.accumulated)}</strong></div>)}</div><div className="account-caption"><ShieldCheck size={17} /><span>{data.mode === "demo" ? "Tài khoản minh họa, chưa kết nối ngân hàng." : "Số dư do bạn thiết lập; Finflow tự cộng/trừ theo giao dịch realtime mới."}</span></div><Button variant="outline" className="wide-button" onClick={() => navigate("accounts")}>Xem tài khoản<ArrowRight size={16} /></Button></section></div></>}
    {view === "accounts" && <section className="bank-grid">{accounts.map(a => <article className="panel bank-detail" key={a.id}><div className="section-heading"><span className="bank-logo vcb"><Landmark /></span><span className="status-pill">{data.mode === "demo" ? "Tài khoản mẫu" : a.active ? "Đang hoạt động" : "Không hoạt động"}</span></div><h2>{a.bank_short_name}</h2><p>{a.label || "Tài khoản ngân hàng"}</p><span className="bank-number">{a.account_number}</span><p>{a.account_holder_name}</p><div className="bank-balance"><span>Số dư hiện tại</span><strong>{money(a.accumulated)}</strong></div><Button className="wide-button" variant="outline" onClick={() => { setBank(a.id); navigate("transactions"); }}>Xem giao dịch<ArrowRight size={16} /></Button></article>)}<article className="panel connect-card"><Cable size={30} /><h2>{data.mode === "live" ? "Số dư & kết nối" : "Kết nối ngân hàng"}</h2><p>{data.mode === "live" ? "Cập nhật số dư hiện tại khi ngân hàng không hỗ trợ trả số dư qua SePay." : "Lấy giao dịch từ các tài khoản của bạn qua SePay."}</p><Button onClick={() => setConnect(true)}>{data.mode === "live" ? "Cập nhật số dư" : "Thiết lập kết nối"}</Button></article></section>}
    {(view === "overview" || view === "transactions") && <section className="panel transactions-panel"><div className="section-heading"><div><h2>{view === "overview" ? "Giao dịch gần đây" : "Tất cả giao dịch"}<span className="count-badge">{filtered.length}</span></h2><p>Lịch sử thu chi từ các tài khoản ngân hàng</p></div><Button variant="outline" onClick={exportCsv} disabled={!filtered.length}><Download size={16} />Xuất CSV</Button></div><div className="table-toolbar"><div className="type-filters" role="group" aria-label="Loại giao dịch">{[{ value: "all", label: "Tất cả" }, { value: "in", label: "Tiền vào" }, { value: "out", label: "Tiền ra" }].map(k => <Button key={k.value} variant="ghost" aria-pressed={kind === k.value} className={kind === k.value ? "selected" : ""} onClick={() => { setKind(k.value); setPage(1); }}>{k.label}</Button>)}</div><div className="search-control"><Search size={17} /><Input aria-label="Tìm giao dịch" placeholder="Tìm nội dung, mã giao dịch…" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} /></div></div>
      <Table><TableHeader><TableRow><TableHead>Nội dung giao dịch</TableHead><TableHead>Ngân hàng</TableHead><TableHead>Thời gian</TableHead><TableHead>Loại</TableHead><TableHead className="amount-cell">Số tiền</TableHead><TableHead><span className="sr-only">Chi tiết</span></TableHead></TableRow></TableHeader><TableBody>{shown.map(t => <TableRow key={t.id}><TableCell><div className="transaction-name"><span className={`transaction-icon ${t.transfer_type === "in" ? "positive" : "negative"}`}>{t.transfer_type === "in" ? <ArrowDownLeft size={19} /> : <ArrowUpRight size={19} />}</span><div><strong>{t.transaction_content || "Giao dịch ngân hàng"}</strong><span>{t.reference_number}</span></div></div></TableCell><TableCell><span className="table-bank">{t.bank_brand_name}</span><span className="cell-secondary">•••• {t.account_number.slice(-4)}</span></TableCell><TableCell>{dateText(t.transaction_date)}</TableCell><TableCell><span className={`type-badge ${t.transfer_type === "in" ? "positive" : "negative"}`}>{t.transfer_type === "in" ? "Tiền vào" : "Tiền ra"}</span></TableCell><TableCell className={`amount-cell ${t.transfer_type === "in" ? "positive" : "negative"}`}>{t.transfer_type === "in" ? "+" : "−"}{money(t.amount_in || t.amount_out)}</TableCell><TableCell><Button variant="ghost" size="icon" aria-label={`Chi tiết ${t.reference_number}`} onClick={() => setDetail(t)}><ChevronRight size={16} /></Button></TableCell></TableRow>)}</TableBody></Table>
      {!shown.length && <div className="empty-state"><Search size={28} /><h3>Chưa có giao dịch phù hợp</h3><p>Thử thay đổi từ khóa, tài khoản hoặc tháng xem.</p><Button variant="outline" onClick={() => { setSearch(""); setKind("all"); setBank("all"); setPage(1); }}>Xóa bộ lọc</Button></div>}
      <div className="table-footer"><span>{filtered.length ? `${(page - 1) * 6 + 1}–${Math.min(page * 6, filtered.length)} trong ${filtered.length} giao dịch` : "0 giao dịch"}</span><div><Button variant="outline" size="icon" aria-label="Trang trước" disabled={page <= 1} onClick={() => setPage(p => p - 1)}><ChevronLeft size={16} /></Button><span>{page} / {pages}</span><Button variant="outline" size="icon" aria-label="Trang sau" disabled={page >= pages} onClick={() => setPage(p => p + 1)}><ChevronRight size={16} /></Button></div></div></section>}
    <AccountPanel plans={planConfig} plansVisible={view === "plans"} open={connect} onOpenChange={setConnect} onIdentity={setIdentity} onConnected={() => { setConnect(false); void sync(); }} onSignedOut={() => { setData(demoData(month)); setIdentity(null); setBank("all"); setPage(1); setError(""); setNotice(""); }} />
    <footer className="page-footer"><span>{settings.brand_name}<span className="brand-dot">.</span><span> Tài chính trong tầm tay</span></span></footer></main></div>
    <Dialog open={!!detail} onOpenChange={open => { if (!open) setDetail(null); }}><DialogContent><DialogHeader><DialogTitle>Chi tiết giao dịch</DialogTitle><DialogDescription>{detail?.reference_number}</DialogDescription></DialogHeader>{detail && <><strong className={`detail-amount ${detail.transfer_type === "in" ? "positive" : "negative"}`}>{detail.transfer_type === "in" ? "+" : "−"}{money(detail.amount_in || detail.amount_out)}</strong><dl className="detail-list"><div><dt>Nội dung</dt><dd>{detail.transaction_content}</dd></div><div><dt>Thời gian</dt><dd>{dateText(detail.transaction_date)} (GMT+7)</dd></div><div><dt>Ngân hàng</dt><dd>{detail.bank_brand_name}</dd></div><div><dt>Số tài khoản</dt><dd>{detail.account_number}</dd></div><div><dt>Nguồn</dt><dd>{data.mode === "demo" ? "Dữ liệu mẫu" : "SePay API v2"}</dd></div></dl></>}</DialogContent></Dialog>
  </div>;
}
